### PR TITLE
Update SR/ES CI setup

### PR DESCRIPTION
**Pull request by ownia**
- Change CI checkout to single commit fetch
- Use 'git apply' to patch linux-acs
- Add SR/ES CI setup

### CODE REVIEW

**Comment by ownia** [comment]
I have tried to runing it twice and got this result:
| |  IR   | SR  | ES |
| ---- | ---- |  ----  | ----  |
| 1st |  5h 33m 24s |  2h 12m 1s | 2h 4m 0s |
| 2nd | 4h 37m 9s  | 2h 7m 52s | 2h 2m 32s |


For a complete CI flow example, you can check:
SR: https://github.com/ownia/arm-systemready/actions/runs/6081803944
IR: https://github.com/ownia/arm-systemready/actions/runs/6081803943
ES: https://github.com/ownia/arm-systemready/actions/runs/6081803948

**Comment by amrathesh** [comment]
Hello @ownia 

As we consistently utilise "git am" across ACS projects, could you please incorporate the following pseudo git configurations into your YML? I believe it will ensure that there are no issues when merging with git am:

```
git config --global user.name "arm-systemready"
git config --global user.email "support-systemready-acs@arm.com"
```

Thank you!
ACS Team

**Comment by ownia** [comment]
Hi @amrathesh. No problem, I will update this commit.

**Comment by chetan-rathore** [comment]
Thanks @ownia for the CI setup scripts.

**Pull request merged**
